[package]
name = "cairo-prove"
version.workspace = true
edition.workspace = true

[dependencies]
prover-sdk.workspace = true
clap.workspace = true
url.workspace = true
serde.workspace = true
thiserror.workspace = true
common.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
reqwest.workspace = true
ed25519-dalek.workspace = true
starknet-types-core.workspace = true